export const fixture = [
  {
    id: 1,
    title: "The Matrix",
    type: "movie",
    genre: "Science Fiction",
    releaseYear: 1999,
    rating: 8.7,
  },
  {
    id: 2,
    title: "Stranger Things",
    type: "tv-show",
    genre: "Drama",
    releaseYear: 2016,
    rating: 8.8,
  },
  {
    id: 3,
    title: "The Witcher 3: Wild Hunt",
    type: "game",
    genre: "Action RPG",
    releaseYear: 2015,
    rating: 9.8,
  },
  {
    id: 4,
    title: "Inception",
    type: "movie",
    genre: "Action",
    releaseYear: 2010,
    rating: 8.8,
  },
  {
    id: 5,
    title: "Breaking Bad",
    type: "tv-show",
    genre: "Crime",
    releaseYear: 2008,
    rating: 9.5,
  },
  {
    id: 6,
    title: "Assassin's Creed Odyssey",
    type: "game",
    genre: "Action RPG",
    releaseYear: 2018,
    rating: 8.6,
  },
  {
    id: 7,
    title: "The Dark Knight",
    type: "movie",
    genre: "Action",
    releaseYear: 2008,
    rating: 9.0,
  },
  {
    id: 8,
    title: "Game of Thrones",
    type: "tv-show",
    genre: "Fantasy",
    releaseYear: 2011,
    rating: 9.3,
  },
  {
    id: 9,
    title: "Red Dead Redemption 2",
    type: "game",
    genre: "Action Adventure",
    releaseYear: 2018,
    rating: 9.7,
  },
  {
    id: 10,
    title: "Pulp Fiction",
    type: "movie",
    genre: "Crime",
    releaseYear: 1994,
    rating: 8.9,
  },
  {
    id: 11,
    title: "The Mandalorian",
    type: "tv-show",
    genre: "Science Fiction",
    releaseYear: 2019,
    rating: 8.7,
  },
  {
    id: 12,
    title: "Minecraft",
    type: "game",
    genre: "Sandbox",
    releaseYear: 2011,
    rating: 9.0,
  },
  {
    id: 13,
    title: "The Shawshank Redemption",
    type: "movie",
    genre: "Drama",
    releaseYear: 1994,
    rating: 9.3,
  },
  {
    id: 14,
    title: "Friends",
    type: "tv-show",
    genre: "Comedy",
    releaseYear: 1994,
    rating: 8.5,
  },
  {
    id: 15,
    title: "Overwatch",
    type: "game",
    genre: "First-person Shooter",
    releaseYear: 2016,
    rating: 8.0,
  },
  {
    id: 16,
    title: "Forrest Gump",
    type: "movie",
    genre: "Drama",
    releaseYear: 1994,
    rating: 8.8,
  },
  {
    id: 17,
    title: "The Office",
    type: "tv-show",
    genre: "Comedy",
    releaseYear: 2005,
    rating: 8.9,
  },
  {
    id: 18,
    title: "Uncharted 4: A Thief's End",
    type: "game",
    genre: "Action Adventure",
    releaseYear: 2016,
    rating: 9.5,
  },
  {
    id: 19,
    title: "The Godfather",
    type: "movie",
    genre: "Crime",
    releaseYear: 1972,
    rating: 9.2,
  },
  {
    id: 20,
    title: "Stranger Things 2",
    type: "tv-show",
    genre: "Drama",
    releaseYear: 2017,
    rating: 8.9,
  },
  {
    id: 21,
    title: "Cyberpunk 2077",
    type: "game",
    genre: "Action RPG",
    releaseYear: 2020,
    rating: 7.2,
  },
  {
    id: 22,
    title: "The Shawshank Redemption",
    type: "movie",
    genre: "Drama",
    releaseYear: 1994,
    rating: 9.3,
  },
  {
    id: 23,
    title: "The Simpsons",
    type: "tv-show",
    genre: "Animation",
    releaseYear: 1989,
    rating: 8.7,
  },
  {
    id: 24,
    title: "The Legend of Zelda: Breath of the Wild",
    type: "game",
    genre: "Action Adventure",
    releaseYear: 2017,
    rating: 9.5,
  },
  {
    id: 25,
    title: "The Revenant",
    type: "movie",
    genre: "Adventure",
    releaseYear: 2015,
    rating: 8.0,
  },
];
